### ISSUE TITLE
Manage multiple servers

### ISSUE THREAD

**Issue by rockinprogramerdude** [Zerefdev/fivemLinux#1]
This is great! It would be awesome to have the ability to manage many instances of FiveM from this one script. Not sure how easy that would be.

**Comment by Zerefdev** [comment]
I don't think it is worth it.
You could create another bash script that wraps multiple copies of my script.

**Comment by zerefdev** [comment]
I don't think it is worth it.
You could create another bash script that wraps multiple copies of my script.
